problem54: str_utils.o hand_utils.o main.o
	gcc -g -Wall -ansi -pedantic hand_utils.o str_utils.o main.o -o problem54

main.o: main.c
	gcc -c -g -Wall -ansi -pedantic main.c -o main.o
	
hand_utils.o: hand_utils.c
	gcc -c -g -Wall -ansi -pedantic hand_utils.c -o hand_utils.o

str_utils.o: str_utils.c
	gcc -c -g -Wall -ansi -pedantic str_utils.c -o str_utils.o
